### ISSUE TITLE
expressive code theme through ec.config.mjs not respected

### ISSUE THREAD

**Issue by o-az** [HiDeoo/starlight-theme-rapide#13]
### Describe the bug

keeping this short: after https://github.com/HiDeoo/starlight-theme-rapide/issues/10 was fixed, now it's possible to configure expressive code theme and stuff but only through astro.config.ts. However, ec.config.mjs file seems to be fully ignored

### To Reproduce

setup ec theme through ec.config.mjs

### Expected behavior

should respect theme choice

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for the feedback 🙌 

I've opened a [Discord discussion](https://discord.com/channels/830184174198718474/1294315714278330388) to talk about this as this will probably require some kind of upstream change to support this use-case.

**Comment by HiDeoo** [comment]
The issue should now be fixed in Expressive Code [v0.38.0](https://expressive-code.com/releases/#0380) which adds a new config merging functionality to `astro-expressive-code`.

This new version should be soon shipped with Starlight or if you don't want to wait, you can manually upagrade, e.g. using an [`override`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) mechanism depending on your package manager.
